CREATE TABLE t_links (
    c_id INT PRIMARY KEY AUTO_INCREMENT,
    c_link VARCHAR(256) NOT NULL,
    c_original VARCHAR(256) NOT NULL,
    c_rank DOUBLE,
    c_count BIGINT,
    c_last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);